/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyProject;

import java.awt.*;
import java.awt.event.*;
import java.text.*;
import javax.swing.Timer;
import javax.swing.*;

/**
 *
 * @author Md. Younus Hossain Ahsan
 */

public class Verify extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
    
    String Verification_Code;
    int quick = 1;
    int verified = 0;
    Timer timer;
    int dec = 0;
    int sec = 30;
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");
    
    public Verify() {
         initComponents();
    }
    
    public Verify(String From) {
        initComponents();
        this.Verification_Code = JClasses.VericationCodeSend.Verification_Code;
        
        timer = new Timer(250, new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e) {
                
                if(verified == 0)
                {
                    dec++;
                
                    if(dec % 4 == 0){
                        sec--;
                        if(sec==0){
                            if(From.equals("Sign IN")){
                                try {
                                    new SignIN().setVisible(true);
                                } catch (ClassNotFoundException ex) {
                                }
                            }

                            dispose();
                        }  
                    }

                    if(sec>9){
                        Count_Down.setForeground(Color.black);
                        Count_Down.setText("00:"+sec);

                    }else{
                        quick = quick * (-1);

                        if(quick == 1){
                            Count_Down.setForeground(Color.red);
                            Count_Down.setText("00:0"+sec);

                        }else if(quick == -1)
                            Count_Down.setText("");
                    } 
                }
                              
                java.util.Date CurrentDate = new java.util.Date();
                Date.setText(sdf.format(CurrentDate));
                
            }

            private void setVisible(boolean b) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        timer.start();
        
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Date = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Count_Down = new javax.swing.JTextField();
        VerificationCode = new javax.swing.JTextField();
        Back = new javax.swing.JButton();
        Verify = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Date.setEditable(false);
        Date.setBackground(new java.awt.Color(249, 245, 242));
        Date.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Date.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Date.setBorder(null);
        Date.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Date.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DateFocusGained(evt);
            }
        });
        Date.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DateMouseClicked(evt);
            }
        });
        Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateActionPerformed(evt);
            }
        });
        getContentPane().add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 190, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 255, 255));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 250, 20));

        Count_Down.setEditable(false);
        Count_Down.setBackground(new java.awt.Color(249, 245, 242));
        Count_Down.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Count_Down.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Count_Down.setBorder(null);
        Count_Down.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Count_Down.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Count_DownFocusGained(evt);
            }
        });
        Count_Down.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Count_DownMouseClicked(evt);
            }
        });
        Count_Down.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Count_DownActionPerformed(evt);
            }
        });
        getContentPane().add(Count_Down, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 130, 34));

        VerificationCode.setBackground(new java.awt.Color(249, 245, 242));
        VerificationCode.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        VerificationCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        VerificationCode.setText("Enter the verification code");
        VerificationCode.setBorder(null);
        VerificationCode.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        VerificationCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                VerificationCodeFocusGained(evt);
            }
        });
        VerificationCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VerificationCodeMouseClicked(evt);
            }
        });
        VerificationCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerificationCodeActionPerformed(evt);
            }
        });
        getContentPane().add(VerificationCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 250, 34));

        Back.setBackground(new java.awt.Color(249, 245, 242));
        Back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Back.setText("Back");
        Back.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Back.setContentAreaFilled(false);
        Back.setOpaque(true);
        Back.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BackMouseMoved(evt);
            }
        });
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BackMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BackMouseReleased(evt);
            }
        });
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 100, 40));

        Verify.setBackground(new java.awt.Color(249, 245, 242));
        Verify.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Verify.setText("Verify");
        Verify.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Verify.setContentAreaFilled(false);
        Verify.setOpaque(true);
        Verify.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                VerifyMouseMoved(evt);
            }
        });
        Verify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VerifyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VerifyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VerifyMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                VerifyMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                VerifyMouseReleased(evt);
            }
        });
        Verify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerifyActionPerformed(evt);
            }
        });
        getContentPane().add(Verify, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 100, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Verification.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Count_DownFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Count_DownFocusGained

    }//GEN-LAST:event_Count_DownFocusGained

    private void Count_DownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Count_DownMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_Count_DownMouseClicked

    private void Count_DownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Count_DownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Count_DownActionPerformed

    private void VerificationCodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_VerificationCodeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_VerificationCodeFocusGained

    private void VerificationCodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerificationCodeMouseClicked
        VerificationCode.setText("");
    }//GEN-LAST:event_VerificationCodeMouseClicked

    private void VerificationCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerificationCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VerificationCodeActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed

        this.setVisible(false);
    }//GEN-LAST:event_BackActionPerformed

    private void VerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerifyActionPerformed

        if(VerificationCode.getText().trim().isEmpty() || VerificationCode.getText().equals("Enter the verification code"))
        {
            JOptionPane.showMessageDialog(null, "Enter the verification code !");
        }
        else if(VerificationCode.getText().equals(Verification_Code))
        {
            verified = 1;
            JOptionPane.showMessageDialog(null, "Verified !");
            new Menu().setVisible(true);
            dispose();
            
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Entered code is wrong !!! Check again ...");
        }
    }//GEN-LAST:event_VerifyActionPerformed

    private void DateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DateFocusGained
        
    }//GEN-LAST:event_DateFocusGained

    private void DateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DateMouseClicked
        
    }//GEN-LAST:event_DateMouseClicked

    private void DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateActionPerformed

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        
    }//GEN-LAST:event_BackMouseClicked

    private void BackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseEntered
        
    }//GEN-LAST:event_BackMouseEntered

    private void BackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseExited
        
    }//GEN-LAST:event_BackMouseExited

    private void BackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMousePressed
        
    }//GEN-LAST:event_BackMousePressed

    private void BackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseReleased
        
    }//GEN-LAST:event_BackMouseReleased

    private void VerifyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerifyMouseClicked
        
    }//GEN-LAST:event_VerifyMouseClicked

    private void VerifyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerifyMouseEntered
        
    }//GEN-LAST:event_VerifyMouseEntered

    private void VerifyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerifyMouseExited
        
    }//GEN-LAST:event_VerifyMouseExited

    private void VerifyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerifyMousePressed
        
    }//GEN-LAST:event_VerifyMousePressed

    private void VerifyMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerifyMouseReleased
        
    }//GEN-LAST:event_VerifyMouseReleased

    private void BackMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseMoved
        Back.setCursor(SignIN.cursor);
    }//GEN-LAST:event_BackMouseMoved

    private void VerifyMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerifyMouseMoved
        Verify.setCursor(SignIN.cursor);
    }//GEN-LAST:event_VerifyMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Verify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Verify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Verify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Verify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Verify().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField Count_Down;
    private javax.swing.JTextField Date;
    private javax.swing.JTextField VerificationCode;
    private javax.swing.JButton Verify;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
